
ALTER TABLE public.premium_page_settings
  ADD COLUMN IF NOT EXISTS modules_eyebrow text DEFAULT '',
  ADD COLUMN IF NOT EXISTS modules_headline text DEFAULT '',
  ADD COLUMN IF NOT EXISTS modules_list jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS trainer_eyebrow text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_name text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_title text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_bio text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_stat_1 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_stat_2 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_stat_3 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS trainer_image_url text DEFAULT '',
  ADD COLUMN IF NOT EXISTS audience_eyebrow text DEFAULT '',
  ADD COLUMN IF NOT EXISTS audience_tags jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS pricing_eyebrow text DEFAULT '',
  ADD COLUMN IF NOT EXISTS pricing_cta_label text DEFAULT '',
  ADD COLUMN IF NOT EXISTS pricing_cta_url text DEFAULT '',
  ADD COLUMN IF NOT EXISTS pricing_supporting_line text DEFAULT '',
  ADD COLUMN IF NOT EXISTS closing_headline text DEFAULT '',
  ADD COLUMN IF NOT EXISTS closing_subheadline text DEFAULT '',
  ADD COLUMN IF NOT EXISTS closing_cta_label text DEFAULT '',
  ADD COLUMN IF NOT EXISTS closing_cta_url text DEFAULT '',
  ADD COLUMN IF NOT EXISTS closing_partner_cta_label text DEFAULT '';
